using System.Collections.Generic;
using System.Linq;
using UnityEngine;
namespace BackpackRTS {
public partial class PrototypeGame {
 Fighter selectedUnit;GameObject selectionRoot;readonly Dictionary<Renderer,Material> originalMaterials=new Dictionary<Renderer,Material>();readonly Dictionary<Material,Material> fadeMaterials=new Dictionary<Material,Material>();readonly List<LineRenderer> rings=new List<LineRenderer>();int ringCount;
 void Ring(Vector2 at,float radius,Color color,float width=.035f){if(selectionRoot==null)selectionRoot=new GameObject("Selection overlays");LineRenderer line;if(ringCount>=rings.Count){var go=new GameObject("Range or candidate");go.transform.SetParent(selectionRoot.transform);line=go.AddComponent<LineRenderer>();line.useWorldSpace=true;line.loop=true;line.positionCount=64;line.sharedMaterial=new Material(Resources.Load<Shader>("PlacementGhost"));line.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;rings.Add(line);}else line=rings[ringCount];ringCount++;line.gameObject.SetActive(true);line.sharedMaterial.color=color;line.startWidth=line.endWidth=width;for(int i=0;i<64;i++){float a=i*Mathf.PI*2/64;line.SetPosition(i,World(at+new Vector2(Mathf.Cos(a),Mathf.Sin(a))*radius,.14f));}}
 void SelectionVisuals(){ringCount=0;if(selectedUnit!=null&&(!selectedUnit.alive||selectedUnit.field!=field))selectedUnit=null;Building source=mergeSource??selected;if(source!=null&&(!source.alive||source.field!=field)){selected=null;mergeSource=null;source=null;}bool active=!paused&&!help&&sim.result==-2;string card=selectedCard>=0?sim.players[0].hand[selectedCard]:null;
  foreach(var key in originalMaterials.Keys.Where(k=>k==null).ToArray())originalMaterials.Remove(key);
  foreach(var b in sim.buildings.Where(b=>b.alive&&b.field==field)){if(!views.TryGetValue(b.id,out var go))continue;bool candidate=active&&(source!=null?sim.CanMerge(source,b):card!=null&&sim.CanMergeCard(0,card,b));bool dim=active&&(source!=null||card!=null&&!catalog.IsSpell(card))&&b!=source&&!candidate;
   foreach(var renderer in go.GetComponentsInChildren<Renderer>()){if(!originalMaterials.TryGetValue(renderer,out var mat)){mat=renderer.sharedMaterial;originalMaterials[renderer]=mat;}if(dim){if(!fadeMaterials.TryGetValue(mat,out var fade)){fade=new Material(Resources.Load<Shader>("PlacementGhost"));var c=mat.color;c.a=.35f;fade.color=c;fadeMaterials[mat]=fade;}renderer.sharedMaterial=fade;}else renderer.sharedMaterial=mat;}
   if(candidate){float pulse=.65f+.35f*Mathf.Sin(Time.unscaledTime*5);Ring(b.pos,.44f,new Color(.25f,1,1,pulse),.06f);Ring(b.pos,.52f,new Color(1,.89f,.40f,pulse*.6f),.018f);}
  }
  if(active){if(selected!=null&&catalog.IsTower(selected.kind))Ring(selected.pos,sim.TowerRange(selected),new Color(.55f,.86f,1,.7f));if(selectedUnit!=null)Ring(selectedUnit.pos,.24f,gold);
   if(card!=null&&PointerWorld(pointer,out var at)&&!(gesture.active&&gesture.cancelled)){bool valid=sim.CanUseAt(0,selectedCard,field,at,out var why);Color color=valid?new Color(.3f,1,.55f,.75f):new Color(1,.2f,.16f,.75f);if(catalog.IsSpell(card)){Ring(at,catalog.Card(card).radius,color,.05f);foreach(var target in sim.SpellTargets(card,0,field,at))Ring(target.pos,.23f,color,.025f);}else{int x=Mathf.FloorToInt(at.x),y=Mathf.FloorToInt(at.y);var b=sim.At(field,x,y);if(b!=null&&sim.CanMergeCard(0,card,b))Ring(b.pos,.34f,Color.cyan,.08f);else if(catalog.IsTower(card)){var shape=sim.Shape(card);var mock=new Building{kind=card,tier=1,branch=-1};Ring(new Vector2(x+(float)shape.Average(c=>c.x)+.5f,y+(float)shape.Average(c=>c.y)+.5f),sim.TowerRange(mock),color);}}}
  }
  for(int i=ringCount;i<rings.Count;i++)rings[i].gameObject.SetActive(false);
 }
 void UnitInfo(){var f=selectedUnit;if(f==null||!f.alive||f.field!=field){selectedUnit=null;return;}Rect panelRect=new Rect(22,428,315,238);Box(panelRect,new Color(.055f,.085f,.115f,.96f));Text(new Rect(38,440,245,30),f.stats.name+" · "+(f.hero?"영웅":"T"+f.tier),18,gold,true);if(Button(new Rect(286,438,36,30),"×")){selectedUnit=null;Event.current.Use();return;}
  string buffs=(f.hasteUntil>sim.time?"가속 ":"")+(f.poisonUntil>sim.time?"중독 ":"")+(f.shield>0?"보호막":"");string text="체력 "+Mathf.CeilToInt(f.hp)+" / "+Mathf.CeilToInt(f.maxHp)+"   보호막 "+Mathf.CeilToInt(f.shield)+"\n마나: 미사용   ·   처치 "+f.kills+"\n공격력 "+sim.EffectiveDamage(f).ToString("F1")+"   공격 간격 "+sim.AttackInterval(f).ToString("F2")+"초\n사거리 "+f.stats.range.ToString("F2")+"   이동속도 "+f.stats.speed.ToString("F2")+"\n상태: "+(buffs==""?"정상":buffs);if(f.hero){var p=sim.players[f.team];text+="\nLv"+p.heroLevel+" · 경험치 "+p.heroXp+" · 스킬 "+Mathf.CeilToInt(Mathf.Max(0,p.skillAt-sim.time))+"초";}Text(new Rect(38,480,285,177),text,14,ink);if(panelRect.Contains(Event.current.mousePosition)&&(Event.current.type==EventType.MouseDown||Event.current.type==EventType.MouseUp||Event.current.type==EventType.MouseDrag))Event.current.Use();
 }
}
}
