using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;

namespace BackpackRTS {
public class PrototypeGame:MonoBehaviour {
 Catalog catalog;ProgressStore store;BattleSimulation sim;Camera cam;Font font;GUIStyle label,button,title,small;Texture2D white;
 string screen="home",race="Human",notice="";List<string> deck=new List<string>();int map,field,selectedCard=-1;Building selected,mergeSource;bool swapMode,paused,help,paid;int reward;
 float accumulator,holdAt;int holding=-1;string detail="";Rect arena=new Rect(14,116,512,609);GameObject terrainRoot;readonly Dictionary<int,GameObject> views=new Dictionary<int,GameObject>();readonly Dictionary<int,string> viewKeys=new Dictionary<int,string>();readonly Dictionary<string,Material> materials=new Dictionary<string,Material>();int shownField=-1,rockCount=-1;float uiScale;Vector2 uiOffset;
 Color ink=new Color(.91f,.94f,.96f), muted=new Color(.57f,.67f,.74f), panel=new Color(.085f,.13f,.18f), blue=new Color(.19f,.51f,.70f), gold=new Color(.98f,.75f,.31f), red=new Color(.77f,.32f,.27f);
 void Awake(){Application.targetFrameRate=60;Screen.orientation=ScreenOrientation.Portrait;catalog=Catalog.Load();store=new ProgressStore();font=Resources.Load<Font>("NotoSansKR");white=Texture2D.whiteTexture;ChooseRace("Human");SetupCamera();if(Environment.GetCommandLineArgs().Contains("--smoke"))StartCoroutine(Smoke());}
 void SetupCamera(){cam=Camera.main;if(cam==null)cam=new GameObject("Portrait camera").AddComponent<Camera>();cam.tag="MainCamera";cam.clearFlags=CameraClearFlags.SolidColor;cam.backgroundColor=new Color(.055f,.085f,.115f);cam.orthographic=true;cam.nearClipPlane=.1f;cam.farClipPlane=100;cam.transform.position=new Vector3(0,16,-22);cam.transform.LookAt(Vector3.zero);cam.orthographicSize=6.15f;
  var light=new GameObject("Sun").AddComponent<Light>();light.type=LightType.Directional;light.intensity=1.3f;light.color=new Color(1,.95f,.84f);light.transform.rotation=Quaternion.Euler(50,-35,0);light.shadows=LightShadows.Soft;RenderSettings.ambientLight=new Color(.56f,.65f,.75f);QualitySettings.shadowDistance=55;QualitySettings.shadows=ShadowQuality.All;}
 void ChooseRace(string r){race=r;var saved=r=="Human"?store.Data.humanDeck:store.Data.orcDeck;deck=catalog.ValidDeck(r,saved)?new List<string>(saved):catalog.Race(r).Take(4).Select(x=>x.id).ToList();}
 void StartBattle(bool practice){if(!catalog.ValidDeck(race,deck.ToArray())){notice="서로 다른 유닛 4종을 선택하세요";return;}if(race=="Human")store.Data.humanDeck=deck.ToArray();else store.Data.orcDeck=deck.ToArray();store.Write();ClearVisuals();sim=new BattleSimulation(catalog,race,deck.ToArray(),map,practice,store);screen="battle";field=0;shownField=-1;selected=null;mergeSource=null;selectedCard=-1;swapMode=false;paused=false;paid=false;reward=0;accumulator=0;notice="";}
 void Update(){if(screen!="battle"||sim==null)return;if(!paused&&!help){accumulator+=Mathf.Min(Time.deltaTime,.15f);while(accumulator>=.05f){sim.Tick(.05f);accumulator-=.05f;}if(sim.result!=-2&&!paid){reward=sim.result==0?store.Reward(sim.battleId,map,sim.practice):0;paid=reward>=0;}}
  RenderWorld();}
 void OnApplicationPause(bool b){if(b&&screen=="battle")paused=true;}
 void InitStyles(){if(label!=null)return;label=new GUIStyle(GUI.skin.label){font=font,fontSize=17,wordWrap=true,normal={textColor=ink},padding=new RectOffset(0,0,0,0)};small=new GUIStyle(label){fontSize=13};title=new GUIStyle(label){fontSize=29,fontStyle=FontStyle.Bold};button=new GUIStyle(GUI.skin.button){font=font,fontSize=16,wordWrap=true,normal={background=white,textColor=ink},hover={background=white,textColor=Color.white},active={background=white,textColor=Color.white},padding=new RectOffset(6,6,4,4),border=new RectOffset(0,0,0,0)};}
 void Box(Rect r,Color c){var prev=GUI.color;GUI.color=c;GUI.DrawTexture(r,white);GUI.color=prev;}
 void Text(Rect r,string text,int size=17,Color? color=null,bool bold=false){var s=new GUIStyle(size>=25?title:size<=13?small:label){fontSize=size,fontStyle=bold?FontStyle.Bold:FontStyle.Normal};s.normal.textColor=color??ink;GUI.Label(r,text,s);}
 bool Button(Rect r,string t,Color? color=null,bool enabled=true){var p=GUI.backgroundColor;GUI.backgroundColor=color??new Color(.14f,.23f,.30f);GUI.enabled=enabled;bool clicked=GUI.Button(r,t,button);GUI.enabled=true;GUI.backgroundColor=p;return clicked;}
 void OnGUI(){InitStyles();Rect safe=Screen.safeArea;uiScale=Mathf.Min(safe.width/540f,safe.height/960f);uiOffset=new Vector2(safe.x+(safe.width-540*uiScale)/2,Screen.height-safe.yMax+(safe.height-960*uiScale)/2);GUI.matrix=Matrix4x4.TRS(new Vector3(uiOffset.x,uiOffset.y,0),Quaternion.identity,new Vector3(uiScale,uiScale,1));
  if(help){Help();return;}if(screen!="battle"){Box(new Rect(0,0,540,960),new Color(.052f,.084f,.115f));Menu();}else BattleUI();if(help)Help();
 }
 void Menu(){Text(new Rect(28,23,340,22),"BACKPACK  /  RTS",13,gold,true);Text(new Rect(28,55,420,53),screen=="growth"?"유닛 성장":screen=="deck"?"원정대 편성":"작은 전장, 큰 전략",30,ink,true);Text(new Rect(28,109,465,42),"세로형 RTS · 프로토타입 0.2.0",14,muted);
  Box(new Rect(382,20,130,31),panel);Text(new Rect(392,25,110,26),"스톤  "+store.Data.stones,15,gold);
  if(screen=="growth"){GrowthMenu();return;}
  if(Button(new Rect(28,158,232,49),"휴먼   ·   균형과 유연함",race=="Human"?blue:panel))ChooseRace("Human");if(Button(new Rect(280,158,232,49),"오크   ·   느리지만 강하게",race=="Orc"?red:panel))ChooseRace("Orc");
  Text(new Rect(28,222,480,44),race=="Human"?"완만한 성장. 빠르게 전열을 만들고 조합으로 대응합니다.":"높은 비용과 느린 생산. 강한 개체로 좁은 전장을 지배합니다.",15,muted);
  Text(new Rect(28,282,330,28),"전투 덱   "+deck.Count+" / 4",20,ink,true);Text(new Rect(28,317,480,26),"6종 중 서로 다른 4종 선택 · 가격대 제한 없음",13,muted);
  var list=catalog.Race(race);for(int i=0;i<list.Count;i++){var u=list[i];int col=i%2,row=i/2;Rect r=new Rect(28+col*248,354+row*101,236,90);bool chosen=deck.Contains(u.id);Box(r,chosen?new Color(.13f,.25f,.32f):panel);Box(new Rect(r.x,r.y,4,r.height),chosen?gold:new Color(.17f,.23f,.28f));Text(new Rect(r.x+14,r.y+10,180,26),u.name,18,ink,true);Text(new Rect(r.x+14,r.y+42,150,36),u.cost+"G  ·  "+Role(u.role)+"\n"+Profile(u.profile),12,muted);
   if(Button(new Rect(r.x+172,r.y+42,53,34),chosen?"선택":"추가",chosen?blue:panel)){if(chosen)deck.Remove(u.id);else if(deck.Count<4)deck.Add(u.id);else notice="선택한 유닛을 먼저 빼면 다른 유닛을 넣을 수 있습니다";}}
  Text(new Rect(28,674,460,29),"검증 전장",18,ink,true);string[] maps={"01  평야","02  두 다리","03  던전"};for(int i=0;i<3;i++)if(Button(new Rect(28+i*165,716,154,45),maps[i],map==i?blue:panel))map=i;
  if(Button(new Rect(28,790,310,59),"전투 시작  →",blue,deck.Count==4))StartBattle(false);if(Button(new Rect(350,790,162,59),"연습 모드",panel,deck.Count==4))StartBattle(true);
  if(Button(new Rect(28,871,232,44),"에너지스톤 성장"))screen="growth";if(Button(new Rect(280,871,232,44),"플레이 방법"))help=true;
  Text(new Rect(28,932,485,25),notice==""?"엘프 · 언데드 · 좀비는 후속 종족입니다":notice,12,gold);
 }
 string Role(string role){switch(role){case "front":return "전열";case "ranged":return "원거리";case "cavalry":return "기동";case "mage":return "광역";case "support":return "지원";default:return "공성";}}
 string Profile(string s)=>s=="production"?"생산 주기 성장":s=="mixed"?"스탯과 생산 성장":s=="orc"?"개체 성능 성장":"스탯 중심 성장";
 void GrowthMenu(){Text(new Rect(28,165,480,48),"전투가 끝나도 유지됩니다. 각 계열의 모든 티어에 체력·공격력 +3%씩 적용됩니다.",16,muted);var list=catalog.Race(race);for(int i=0;i<list.Count;i++){var u=list[i];int l=store.Level(u.id);Box(new Rect(28,236+i*92,484,80),panel);Text(new Rect(44,249+i*92,285,25),u.name+"   Lv"+l,18);Text(new Rect(44,279+i*92,290,24),"체력·공격력 +"+((l-1)*3)+"%",13,muted);if(Button(new Rect(357,255+i*92,138,43),l==5?"최대 레벨":(l*10)+" 스톤 강화",blue,l<5&&store.Data.stones>=l*10))store.UpgradeUnit(u.id);}if(Button(new Rect(28,843,484,54),"돌아가기"))screen="home";}
 void BattleUI(){if(sim==null)return;var p=sim.players[0];Box(new Rect(0,0,540,108),new Color(.055f,.085f,.115f));Box(new Rect(0,732,540,228),new Color(.055f,.085f,.115f));Text(new Rect(22,15,270,33),race=="Human"?"휴먼 원정대":"오크 원정대",22,ink,true);Text(new Rect(22,57,198,32),"골드 "+Mathf.FloorToInt(p.gold)+"  +"+sim.Income(0).ToString("F2")+"/s",17,gold);if(map==2)Text(new Rect(224,57,107,27),"소울 "+p.soul,16,new Color(.7f,.65f,1));Text(new Rect(332,20,92,29),TimeSpan.FromSeconds(Mathf.Max(0,360-sim.time)).ToString(@"mm\:ss"),23);
  if(Button(new Rect(445,16,73,39),paused?"재개":"정지"))paused=!paused;if(Button(new Rect(445,63,73,33),"도움말"))help=true;
  Text(new Rect(18,111,300,23),field==0?(map==0?"열린 평야":"두 다리 전선"):"고정 적 던전 · 보스만 소울 지급",12,muted);
  DrawBars();if(help)return;if(sim.result!=-2){ResultUI();return;}if(paused){PauseUI();return;}if(sim.practice)Text(new Rect(374,109,160,22),"연습 · 보상 없음",12,gold);
  if(map==2){if(Button(new Rect(16,737,121,38),"일반 필드",field==0?blue:panel)){field=0;selected=null;mergeSource=null;}if(Button(new Rect(147,737,121,38),"던전 필드",field==1?blue:panel)){field=1;selected=null;mergeSource=null;}}
  else Text(new Rect(17,742,247,29),"기지 파괴 시 승리",15,muted);
  if(p.heroUnlocked){var hero=sim.Hero(0);string status=hero==null?"부활 "+Mathf.CeilToInt(Mathf.Max(0,p.reviveAt-sim.time))+"초":"영웅 Lv"+p.heroLevel+" · XP "+p.heroXp;Text(new Rect(280,736,242,20),status,12,gold);if(Button(new Rect(280,759,242,37),sim.time>=p.skillAt?"수호의 함성":"스킬 "+Mathf.CeilToInt(p.skillAt-sim.time)+"초",blue,hero!=null&&sim.time>=p.skillAt))sim.Skill(0);}
  else if(map==2&&Button(new Rect(280,737,242,38),"영웅 소환 · 소울 10",blue,p.soul>=10))sim.Summon(0);
  if(selected!=null&&!selected.alive)selected=null;
  if(selected!=null){SelectionUI();}else{Text(new Rect(17,795,408,30),mergeSource!=null?"합칠 대상 건물을 누르세요":swapMode?"교체할 카드 한 장을 누르세요":selectedCard>=0?"빈 칸을 눌러 건설 · 회전 불가":sim.message,13,gold);}
  string swap=p.swaps>0?(swapMode?"취소":"새로고침"):Mathf.CeilToInt(p.swapReady-sim.time)+"초";if(Button(new Rect(423,804,100,32),swap,swapMode?gold:panel,p.swaps>0)){swapMode=!swapMode;selectedCard=-1;selected=null;mergeSource=null;}
  for(int i=0;i<4;i++){Rect r=new Rect(17+i*129,844,120,99);var id=p.hand[i];bool active=selectedCard==i;Box(r,active?new Color(.18f,.34f,.43f):panel);Box(new Rect(r.x,r.y,r.width,3),active?gold:new Color(.22f,.37f,.43f));
   if(id==null){Text(new Rect(r.x+18,r.y+34,90,28),"보충 중",15,muted);continue;}int cost=sim.Cost(id);var u=catalog.Find(id);Text(new Rect(r.x+10,r.y+9,90,43),u?.name??(id=="mine"?"금광":"방어타워"),14,ink,true);Text(new Rect(r.x+10,r.y+62,52,27),cost+" G",17,p.gold>=cost?gold:muted);MiniShape(new Rect(r.x+77,r.y+63,36,26),sim.Shape(id),active?gold:blue);
   if(Event.current.type==EventType.MouseUp&&r.Contains(Event.current.mousePosition)&&!paused&&!help&&sim.result==-2){if(swapMode){sim.Swap(0,i);swapMode=false;}else{selectedCard=selectedCard==i?-1:i;selected=null;mergeSource=null;}Event.current.Use();}}
  if(selected!=null&&selected.Pending)BranchUI(selected);
  if(sim.practice&&selected==null){if(Button(new Rect(17,680,92,31),"자원 +"))sim.PracticeSetup();if(Button(new Rect(117,680,101,31),"T3 재료"))PracticeMaterials();}
  if(!paused&&!help&&sim.result==-2&&Event.current.type==EventType.MouseUp&&arena.Contains(Event.current.mousePosition)){WorldClick(Event.current.mousePosition);Event.current.Use();}
  if(paused&&sim.result==-2){Modal("일시정지","두 필드, 교체 재충전, 부활 시간이 모두 멈춥니다.");if(Button(new Rect(120,495,300,52),"전투 계속",blue))paused=false;if(Button(new Rect(120,562,300,48),"전투 포기")){ClearVisuals();screen="home";sim=null;}}
  if(sim.result!=-2)ResultUI();
 }
 void MiniShape(Rect r,Cell[] cells,Color c){float size=8;foreach(var a in cells)Box(new Rect(r.x+a.x*(size+1),r.y+a.y*(size+1),size,size),c);}
 void SelectionUI(){string name=selected.kind=="base"?"기지":selected.kind=="mine"?"금광 "+selected.workers+"명":selected.kind=="tower"?"방어타워":catalog.Find(selected.kind).name;Text(new Rect(17,783,270,28),name+" · T"+selected.tier+"  "+Mathf.CeilToInt(selected.hp)+" HP",13,ink);
  if(selected.kind=="mine"){if(Button(new Rect(17,807,133,29),"일꾼 + "+sim.WorkerCost(0)+"G",blue))sim.BuyWorker(selected);}
  else if(selected.kind!="base"&&Button(new Rect(17,807,133,29),"합성 대상 선택",blue,selected.tier<4)){mergeSource=selected;selected=null;}
  if(selected!=null&&selected.kind!="base"&&Button(new Rect(160,807,123,29),"판매 +"+sim.Refund(selected)+"G")){sim.Sell(selected);selected=null;}
  if(selected!=null&&Button(new Rect(293,807,65,29),"닫기"))selected=null;
 }
 void BranchUI(Building b){Vector2 pos=Project(new Vector3(b.pos.x-(field==0?4:3),1.7f,b.pos.y-(field==0?9:5)));float x=Mathf.Clamp(pos.x-155,18,212),y=Mathf.Clamp(pos.y-65,160,635);for(int k=0;k<2;k++){Rect r=new Rect(x+k*158,y,150,47);var u=catalog.Find(b.kind);string name=u!=null?u.Tier(4,k).name:b.kind=="mine"?(k==0?"안전 채굴":"심층 채굴"):(k==0?"속사탑":"장궁탑");Box(r,new Color(.15f,.30f,.38f));Text(new Rect(r.x+8,r.y+10,134,30),name,14,gold,true);
   var e=Event.current;if(e.type==EventType.MouseDown&&r.Contains(e.mousePosition)){holding=k;holdAt=Time.realtimeSinceStartup;e.Use();}if(holding==k&&Time.realtimeSinceStartup-holdAt>=.45f){detail=u!=null?Describe(u.Tier(4,k)):name;Box(new Rect(45,320,450,176),panel);Text(new Rect(62,337,416,145),detail+"\n손을 뗀 뒤 짧게 눌러 선택하세요",16,ink);}
   if(e.type==EventType.MouseUp&&holding==k){if(r.Contains(e.mousePosition)&&Time.realtimeSinceStartup-holdAt<.45f)sim.Choose(b,k);holding=-1;detail="";e.Use();}}
 }
 string Describe(TierDefinition t)=>t.name+"\n체력 "+t.hp+" · 공격 "+t.damage+"\n사거리 "+t.range+" · 공격 "+t.attackInterval+"초\n생산 "+t.spawnInterval.ToString("F2")+"초 · "+EffectName(t.effect);
 string EffectName(string e){switch(e){case "splash":return "광역 공격";case "heal":return "아군 회복";case "shield":return "아군 보호막";case "haste":return "공격 속도 강화";case "charge":return "돌격";case "siege":return "건물 추가 피해";case "berserk":return "체력 절반 이하 광폭";case "antiCavalry":return "기마 추가 피해";case "poison":return "독 피해";case "guard":return "주변 피해 감소";case "shieldbreak":return "보호막 파괴";default:return "기본 공격";}}
 void WorldClick(Vector2 mouse){Vector2 real=new Vector2(uiOffset.x+mouse.x*uiScale,Screen.height-uiOffset.y-mouse.y*uiScale);Ray ray=cam.ScreenPointToRay(real);var plane=new Plane(Vector3.up,Vector3.zero);if(!plane.Raycast(ray,out float enter))return;Vector3 at=ray.GetPoint(enter);int x=Mathf.FloorToInt(at.x+(field==0?4:3)),y=Mathf.FloorToInt(at.z+(field==0?9:5));if(!sim.Inside(field,x,y))return;
  var b=sim.At(field,x,y);if(mergeSource!=null){if(b!=null&&b.team==0&&sim.Merge(mergeSource,b)){selected=b;mergeSource=null;}else if(b==null){sim.message="빈 칸으로 이동할 수 없습니다";mergeSource=null;}return;}
  if(selectedCard>=0){string k=sim.players[0].hand[selectedCard];if(k=="mine"&&field==0){x=x<4?0:6;y=y<9?1:15;}if(sim.PlaceCard(0,selectedCard,field,x,y))selectedCard=-1;return;}
  if(b!=null&&b.team==0){selected=b;return;}selected=null;if(field==0&&sim.Removable(x,y))sim.ClearRock(0,x,y);
 }
 void ResultUI(){string heading=sim.result==0?"승리":sim.result==2?"무승부":"다시 도전하세요";Modal(heading,sim.practice?"연습 종료 · 에너지스톤 보상 없음":sim.result==0?(reward<0?"저장 실패 · 다시 시도합니다":"에너지스톤 +"+reward):"배치와 조합을 바꾸어 다시 도전해 보세요");if(Button(new Rect(120,495,300,53),"다시 도전",blue))StartBattle(sim.practice);if(Button(new Rect(120,565,300,48),"편성으로 돌아가기")){ClearVisuals();sim=null;screen="home";}}
 void PauseUI(){Modal("일시정지","두 필드, 교체 재충전, 부활 시간이 모두 멈춥니다.");if(Button(new Rect(120,495,300,52),"전투 계속",blue))paused=false;if(Button(new Rect(120,562,300,48),"전투 포기")){ClearVisuals();screen="home";sim=null;}}
 void Modal(string heading,string body){Box(new Rect(0,0,540,960),new Color(0,0,0,.68f));Box(new Rect(78,301,384,345),panel);Text(new Rect(105,329,330,63),heading,27,ink,true);Text(new Rect(105,406,330,78),body,17,muted);}
 void Help(){Box(new Rect(0,0,540,960),new Color(.04f,.065f,.09f,.98f));Text(new Rect(32,42,475,52),"플레이 방법",28,ink,true);string instructions="1  종족별 후보에서 유닛 4종을 선택합니다.\n\n2  카드 → 자기 구역의 빈 칸을 눌러 건설합니다. 카드 뽑기는 무료, 건설은 골드입니다. 회전은 없습니다.\n\n3  건물을 누르고 합성 대상을 선택합니다. 같은 건물과 같은 티어만 합칩니다. T4 버블은 길게 눌러 설명, 짧게 눌러 선택합니다.\n\n4  금광을 눌러 일꾼을 추가합니다. 장애물을 누르면 3골드로 제거합니다.\n\n5  새로고침 → 교체할 카드 한 장. 최초 1회, 사용 후 30초에 갱신됩니다.\n\n6  던전 맵에서는 고정 적을 처치합니다. 보스의 소울 10으로 영웅을 소환합니다. 영웅은 처치 경험치로 성장하고 죽으면 20초 뒤 같은 레벨로 부활합니다.\n\n7  적 기지를 파괴하면 승리합니다. 영웅 성장과 골드는 한 판에서만 유지됩니다.";Text(new Rect(32,119,475,729),instructions,17,ink);if(Button(new Rect(32,871,476,53),"확인",blue))help=false;}
 void PracticeMaterials(){if(!sim.practice)return;string k=deck[0];int count=0;for(int y=0;y<=6;y++)for(int x=0;x<8;x++)if(count<2&&sim.CanPlace(k,0,0,x,y,out var why)){var b=sim.AddBuilding(k,0,0,x,y);b.tier=3;b.built=sim.time;b.maxHp=b.hp=catalog.Find(k).buildingHp*2.56f;b.invested=0;count++;}sim.message=count==2?"T3 두 건물을 합쳐 T4를 검증하세요":"재료 공간이 부족합니다";}
 Vector2 Project(Vector3 p){var s=cam.WorldToScreenPoint(p);return new Vector2((s.x-uiOffset.x)/uiScale,(Screen.height-s.y-uiOffset.y)/uiScale);}
 void DrawBars(){if(cam==null)return;foreach(var b in sim.buildings.Where(b=>b.alive&&b.field==field)){var p=Project(new Vector3(b.pos.x-(field==0?4:3),1.3f,b.pos.y-(field==0?9:5)));if(p.y<arena.y+25||p.y>arena.yMax-28)continue;float w=b.kind=="base"?79:42;Box(new Rect(p.x-w/2,p.y,w,5),new Color(.08f,.12f,.12f));Box(new Rect(p.x-w/2,p.y,w*Mathf.Clamp01(b.hp/b.maxHp),5),b.team==0?blue:red);if(b.kind!="base"){Text(new Rect(p.x-20,p.y+7,60,19),"T"+b.tier+(b.Pending?" !":""),11,b.Pending?gold:Color.white);if(b==selected)Box(new Rect(p.x-25,p.y-4,50,2),gold);}}
  foreach(var f in sim.fighters.Where(f=>f.alive&&f.field==field&&(f.hp<f.maxHp||f.hero||f.boss))){var p=Project(World(f.pos,.82f));if(!arena.Contains(p))continue;Box(new Rect(p.x-15,p.y,30,3),panel);Box(new Rect(p.x-15,p.y,30*Mathf.Clamp01(f.hp/f.maxHp),3),f.hero?gold:f.team==0?blue:red);if(f.shield>0)Box(new Rect(p.x-15,p.y+4,30,2),new Color(.7f,.8f,1));}
 }
 Vector3 World(Vector2 pos,float y=0)=>new Vector3(pos.x-(field==0?4:3),y,pos.y-(field==0?9:5));
 void RenderWorld(){cam.rect=new Rect((uiOffset.x)/Screen.width,(Screen.height-uiOffset.y-(arena.y+arena.height)*uiScale)/Screen.height,540*uiScale/Screen.width,arena.height*uiScale/Screen.height);cam.orthographicSize=field==0?7.0f:4.3f;
  if(shownField!=field||rockCount!=sim.removed.Count){RebuildTerrain();shownField=field;rockCount=sim.removed.Count;}
  var alive=new HashSet<int>();foreach(var b in sim.buildings){if(!b.alive||b.field!=field)continue;alive.Add(b.id);string key=b.kind+b.tier+"/"+b.branch;if(!views.ContainsKey(b.id)||viewKeys[b.id]!=key){if(views.TryGetValue(b.id,out var old))Destroy(old);views[b.id]=BuildingModel(b);viewKeys[b.id]=key;}views[b.id].transform.position=World(b.pos);}
  foreach(var f in sim.fighters){if(!f.alive||f.field!=field)continue;alive.Add(f.id);string key=f.kind+f.tier;if(!views.ContainsKey(f.id)){views[f.id]=UnitModel(f);viewKeys[f.id]=key;}var go=views[f.id];go.transform.position=World(f.pos,.035f+Mathf.Sin(Time.time*7+f.id)*.015f);Vector2 target=f.path.Count>0?f.path[0]-f.pos:new Vector2(0,f.team==0?1:-1);if(target.sqrMagnitude>.001f)go.transform.rotation=Quaternion.Euler(0,Mathf.Atan2(target.x,target.y)*Mathf.Rad2Deg,0);}
  foreach(int id in views.Keys.ToArray())if(!alive.Contains(id)){Destroy(views[id]);views.Remove(id);viewKeys.Remove(id);}
 }
 Material Mat(Color c){string key=c.ToString();if(materials.TryGetValue(key,out var m))return m;m=new Material(Resources.Load<Shader>("PrototypeToon"));m.color=c;materials[key]=m;return m;}
 GameObject Part(GameObject root,PrimitiveType type,Vector3 pos,Vector3 scale,Color c){var go=GameObject.CreatePrimitive(type);go.transform.SetParent(root.transform,false);go.transform.localPosition=pos;go.transform.localScale=scale;go.GetComponent<Renderer>().sharedMaterial=Mat(c);var collider=go.GetComponent<Collider>();if(collider!=null)Destroy(collider);return go;}
 void Roof(GameObject root,Vector3 pos,float w,float h,float d,Color color){var go=new GameObject("Roof");go.transform.SetParent(root.transform,false);go.transform.localPosition=pos;var mesh=new Mesh();mesh.vertices=new[]{new Vector3(-w/2,0,-d/2),new Vector3(w/2,0,-d/2),new Vector3(w/2,0,d/2),new Vector3(-w/2,0,d/2),new Vector3(0,h,0)};mesh.triangles=new[]{0,4,1,1,4,2,2,4,3,3,4,0,0,1,2,0,2,3};mesh.RecalculateNormals();go.AddComponent<MeshFilter>().sharedMesh=mesh;go.AddComponent<MeshRenderer>().sharedMaterial=Mat(color);}
 void RebuildTerrain(){if(terrainRoot!=null)Destroy(terrainRoot);terrainRoot=new GameObject("Arena");int w=sim.Width(field),h=sim.Height(field);Part(terrainRoot,PrimitiveType.Cube,new Vector3(0,-.46f,0),new Vector3(w+.35f,.7f,h+.35f),new Color(.18f,.25f,.24f));
  for(int y=0;y<h;y++)for(int x=0;x<w;x++){int t=sim.Terrain(field,x,y);Color c=field==1?new Color(.30f,.31f,.37f):new Color(.36f+(x+y)%2*.025f,.48f+(x+y)%2*.018f,.28f);if(t==1)c=new Color(.59f,.48f,.25f);if(t==2)c=new Color(.20f,.49f,.62f);Vector3 pos=new Vector3(x+.5f-w/2f,-.04f,y+.5f-h/2f);Part(terrainRoot,PrimitiveType.Cube,pos,new Vector3(.975f,.11f,.975f),c);
   if(t==3){Part(terrainRoot,PrimitiveType.Sphere,pos+Vector3.up*.32f,new Vector3(.87f,.8f,.82f),new Color(.39f,.41f,.40f));}
   if(field==0&&map>=1&&y>=8&&y<=9&&t==0){Part(terrainRoot,PrimitiveType.Cube,pos+Vector3.up*.10f,new Vector3(.98f,.10f,.96f),new Color(.60f,.42f,.24f));}
   if(t==1){for(int k=0;k<3;k++)Part(terrainRoot,PrimitiveType.Cube,pos+new Vector3(-.2f+k*.18f,.12f,.08f),new Vector3(.15f,.2f,.22f),new Color(.90f,.71f,.24f));}}
 }
 GameObject BuildingModel(Building b){var root=new GameObject(b.kind+" "+b.id);Color team=b.team==0?new Color(.15f,.43f,.66f):new Color(.67f,.25f,.19f),stone=new Color(.74f,.69f,.55f);bool orc=sim.players[b.team].race=="Orc";if(orc)stone=new Color(.43f,.31f,.22f);
  foreach(var c in b.shape)Part(root,PrimitiveType.Cube,new Vector3(b.x+c.x+.5f-b.pos.x,.09f,b.y+c.y+.5f-b.pos.y),new Vector3(.86f,.18f,.86f),new Color(.30f,.29f,.24f));
  if(b.kind=="base"){Part(root,PrimitiveType.Cube,new Vector3(0,.50f,0),new Vector3(1.32f,1,1.27f),stone);Roof(root,new Vector3(0,1.02f,0),1.5f,.48f,1.4f,team);foreach(float x in new[]{-.69f,.69f})foreach(float z in new[]{-.65f,.65f}){Part(root,PrimitiveType.Cylinder,new Vector3(x,.58f,z),new Vector3(.46f,.57f,.46f),stone);Roof(root,new Vector3(x,1.16f,z),.62f,.33f,.62f,team);}Part(root,PrimitiveType.Cube,new Vector3(0,.30f,-.652f),new Vector3(.38f,.59f,.10f),new Color(.21f,.16f,.11f));}
  else if(b.kind=="mine"){Part(root,PrimitiveType.Sphere,new Vector3(0,.32f,0),new Vector3(1.5f,.85f,1.3f),new Color(.41f,.40f,.35f));Part(root,PrimitiveType.Cube,new Vector3(0,.3f,-.58f),new Vector3(.53f,.61f,.14f),new Color(.15f,.12f,.10f));Roof(root,new Vector3(0,.58f,-.48f),.9f,.34f,.65f,new Color(.62f,.39f,.17f));Part(root,PrimitiveType.Cube,new Vector3(.5f,.55f,-.2f),new Vector3(.25f,.29f,.27f),gold);}
  else if(b.kind=="tower"){Part(root,PrimitiveType.Cylinder,new Vector3(0,.47f,0),new Vector3(.68f,.48f,.68f),stone);Part(root,PrimitiveType.Cube,new Vector3(0,1,0),new Vector3(.88f,.22f,.83f),team);Part(root,PrimitiveType.Cube,new Vector3(0,1.23f,.2f),new Vector3(.13f,.15f,.79f),new Color(.24f,.21f,.17f));}
  else{float w=b.shape.Max(c=>c.x)+.7f,d=b.shape.Max(c=>c.y)+.7f;Part(root,PrimitiveType.Cube,new Vector3(0,.4f,0),new Vector3(w*.75f,.66f,Mathf.Max(.55f,d*.75f)),stone);Roof(root,new Vector3(0,.75f,0),w*.9f,.42f,d*.95f,team);Part(root,PrimitiveType.Cube,new Vector3(0,.35f,-Mathf.Max(.30f,d*.39f)),new Vector3(.30f,.48f,.10f),new Color(.19f,.14f,.10f));}
  Part(root,PrimitiveType.Cylinder,new Vector3(.34f,1.2f,.18f),new Vector3(.045f,.62f,.045f),new Color(.35f,.24f,.12f));Part(root,PrimitiveType.Cube,new Vector3(.49f,1.64f,.18f),new Vector3(.34f,.23f,.025f),b.tier==4?gold:team);return root;
 }
 GameObject UnitModel(Fighter f){var root=new GameObject(f.kind+" "+f.id);bool orc=f.kind.StartsWith("O")||f.boss;Color skin=orc?new Color(.40f,.57f,.24f):new Color(.89f,.67f,.47f),cloth=f.team==0?blue:red;float scale=f.boss?1.7f:f.hero?1.2f:1+f.tier*.07f;var def=catalog.Find(f.kind);bool horse=def?.role=="cavalry";
  Part(root,PrimitiveType.Cylinder,new Vector3(0,.025f,0),new Vector3(.52f,.013f,.52f),f.hero?gold:cloth);
  if(horse){Part(root,PrimitiveType.Capsule,new Vector3(0,.23f,0),new Vector3(.3f,.22f,.6f),new Color(.36f,.22f,.13f));}
  float lift=horse? .23f:0;Part(root,PrimitiveType.Capsule,new Vector3(0,.29f+lift,0),new Vector3(.31f,.23f,.23f),cloth);Part(root,PrimitiveType.Sphere,new Vector3(0,.60f+lift,0),new Vector3(.35f,.35f,.31f),skin);
  Part(root,PrimitiveType.Cube,new Vector3(-.08f,.13f+lift,0),new Vector3(.10f,.20f,.13f),new Color(.2f,.16f,.13f));Part(root,PrimitiveType.Cube,new Vector3(.08f,.13f+lift,0),new Vector3(.10f,.20f,.13f),new Color(.2f,.16f,.13f));
  if(def?.role=="mage"||def?.role=="support"){Part(root,PrimitiveType.Cylinder,new Vector3(.22f,.40f+lift,.1f),new Vector3(.045f,.37f,.045f),new Color(.44f,.27f,.13f));Part(root,PrimitiveType.Sphere,new Vector3(.22f,.81f+lift,.1f),new Vector3(.16f,.16f,.16f),new Color(.51f,.78f,.99f));Roof(root,new Vector3(0,.72f+lift,0),.39f,.24f,.35f,cloth);}
  else if(f.stats.range>1){Part(root,PrimitiveType.Cube,new Vector3(.16f,.40f+lift,.20f),new Vector3(.09f,.12f,.47f),new Color(.4f,.28f,.17f));}
  else{Part(root,PrimitiveType.Cube,new Vector3(.23f,.49f+lift,.1f),new Vector3(.085f,.42f,.10f),f.tier>=3||f.hero?new Color(.72f,.76f,.78f):new Color(.43f,.28f,.14f));Part(root,PrimitiveType.Cube,new Vector3(-.20f,.36f+lift,.02f),new Vector3(.08f,.31f,.29f),cloth);}
  if(f.tier>=3||f.hero)Part(root,PrimitiveType.Cube,new Vector3(0,.74f+lift,0),new Vector3(.32f,.13f,.31f),f.hero?gold:new Color(.47f,.51f,.55f));root.transform.localScale=Vector3.one*scale;return root;
 }
 void ClearVisuals(){foreach(var go in views.Values)if(go!=null)Destroy(go);views.Clear();viewKeys.Clear();if(terrainRoot!=null)Destroy(terrainRoot);shownField=-1;}
 IEnumerator Smoke(){string dir=Path.Combine(Application.dataPath,"../../artifacts");var args=Environment.GetCommandLineArgs();int index=Array.IndexOf(args,"--capture-dir");if(index>=0&&index+1<args.Length)dir=args[index+1];Directory.CreateDirectory(dir);yield return new WaitForSeconds(1);ScreenCapture.CaptureScreenshot(Path.Combine(dir,"home.png"));yield return new WaitForSeconds(1);map=2;StartBattle(true);
  for(int i=0;i<3;i++){bool done=false;for(int y=3;y<=6&&!done;y++)for(int x=0;x<8&&!done;x++)if(sim.CanPlace(sim.players[0].hand[i],0,0,x,y,out var why))done=sim.PlaceCard(0,i,0,x,y);}
  yield return new WaitForSeconds(12);ScreenCapture.CaptureScreenshot(Path.Combine(dir,"battle.png"));yield return new WaitForSeconds(1);field=1;yield return new WaitForSeconds(1);ScreenCapture.CaptureScreenshot(Path.Combine(dir,"dungeon.png"));yield return new WaitForSeconds(1);field=0;PracticeMaterials();selected=sim.buildings.LastOrDefault(b=>b.team==0&&b.tier==3);var other=sim.buildings.FirstOrDefault(b=>b.team==0&&b.tier==3&&b!=selected);if(other!=null&&selected!=null)sim.Merge(other,selected);yield return new WaitForSeconds(1);ScreenCapture.CaptureScreenshot(Path.Combine(dir,"merge.png"));yield return new WaitForSeconds(2);File.WriteAllText(Path.Combine(dir,"runtime-smoke.json"),"{\"version\":\"0.2.0\",\"time\":"+sim.time.ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"fighters\":"+sim.fighters.Count+",\"result\":"+sim.result+"}");Application.Quit();}
 }
}
