using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEditor.Build.Reporting;
using UnityEngine;
using BackpackRTS;

public static class PrototypeBuild {
 static string Root=>Directory.GetParent(Application.dataPath).FullName;
 static readonly List<string> checks=new List<string>();
 static void Check(bool yes,string name){if(!yes)throw new Exception("FAILED: "+name);checks.Add(name);Debug.Log("PASS: "+name);}
 public static void Configure(){PlayerSettings.companyName="RTS Prototype";PlayerSettings.productName="Backpack RTS";PlayerSettings.bundleVersion="0.2.0";PlayerSettings.defaultScreenWidth=540;PlayerSettings.defaultScreenHeight=960;PlayerSettings.fullScreenMode=FullScreenMode.Windowed;PlayerSettings.resizableWindow=false;PlayerSettings.defaultInterfaceOrientation=UIOrientation.Portrait;PlayerSettings.allowedAutorotateToLandscapeLeft=false;PlayerSettings.allowedAutorotateToLandscapeRight=false;PlayerSettings.allowedAutorotateToPortraitUpsideDown=false;PlayerSettings.runInBackground=false;
  PlayerSettings.SetApplicationIdentifier(UnityEditor.Build.NamedBuildTarget.Android,"com.hdh853.rtsproto");PlayerSettings.Android.minSdkVersion=AndroidSdkVersions.AndroidApiLevel26;PlayerSettings.Android.targetSdkVersion=AndroidSdkVersions.AndroidApiLevel35;
  var scene=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);new GameObject("Backpack RTS").AddComponent<PrototypeGame>();Directory.CreateDirectory(Path.Combine(Application.dataPath,"Scenes"));EditorSceneManager.SaveScene(scene,"Assets/Scenes/Boot.unity");EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene("Assets/Scenes/Boot.unity",true)};AssetDatabase.SaveAssets();}
 [MenuItem("Prototype/Validate rules")]
 public static void Validate(){checks.Clear();var c=Catalog.Load();var deck=new[]{"H01","H02","H03","H04"};Check(c.units.Length==12,"12 extensible unit definitions");Check(c.units.All(u=>u.tiers.Length==5&&u.tiers.All(t=>t.hp>0&&t.damage>0&&t.spawnInterval>0)),"60 explicit tier records");Check(c.ValidDeck("Human",deck)&&!c.ValidDeck("Human",new[]{"H01","H01","H03","H04"})&&!c.ValidDeck("Orc",deck),"deck uniqueness and faction validation");
  var w=new BattleSimulation(c,"Human",deck,2,true){enableAI=false};Check(w.players[0].swaps==1,"initial refresh credit");Check(w.Swap(0,0),"refresh consumes one card");w.Tick(29.9f);Check(w.players[0].swaps==0,"refresh unavailable before 30 seconds");w.Tick(.11f);Check(w.players[0].swaps==1,"refresh recovers after 30 seconds");w.Tick(60);Check(w.players[0].swaps==1,"refresh does not accumulate");
  var a=new BattleSimulation(c,"Human",deck,0,true){enableAI=false};var gold=a.players[0].gold;var card=a.players[0].hand[0];Check(!a.PlaceCard(0,0,0,3,0)&&a.players[0].gold==gold&&a.players[0].hand[0]==card,"invalid placement preserves card and gold");Check(a.PlaceCard(0,0,0,0,3),"fixed footprint placement");Check(a.At(0,1,3)!=null&&a.At(0,0,4)==null,"footprint has fixed orientation");
  a.Tick(1.1f);var b1=a.At(0,0,3);var b2=a.AddBuilding("H01",0,0,3,3);a.Tick(1.1f);b1.hp=b1.maxHp*.5f;b1.progress=6;b2.progress=2;Check(a.Merge(b1,b2),"matching buildings merge");Check(b2.tier==2&&Mathf.Abs(b2.hp/b2.maxHp-.75f)<.001f&&!b1.alive,"merge preserves weighted health and removes source");Check(Mathf.Abs(b2.progress-2)<.01f,"stat-only tier preserves production interval");Check(c.Find("H06").tiers[2].spawnInterval<c.Find("H06").tiers[0].spawnInterval*.5f,"production-specific growth independent of HP");
  var mine=a.buildings.First(b=>b.team==0&&b.kind=="mine");Check(a.BuyWorker(mine)&&mine.workers==2&&!a.BuyWorker(mine),"worker purchase obeys mine capacity");
  var d=new BattleSimulation(c,"Human",deck,2,true){enableAI=false};int initial=d.fighters.Count(f=>f.team==2);for(int i=0;i<100;i++)d.Tick(.05f);Check(initial==5&&d.fighters.Count(f=>f.alive&&f.team==2)==5,"dungeon has exactly five fixed enemies without spawns");d.fighters.First(f=>f.team==2&&!f.boss).hp=0;d.Tick(.05f);Check(d.players[0].soul==0,"ordinary dungeon kill yields no souls");d.fighters.First(f=>f.boss).hp=0;d.Tick(.05f);Check(d.players[0].soul==10,"boss grants ten souls once");d.Tick(.05f);Check(d.players[0].soul==10,"boss reward not duplicated");Check(d.Summon(0)&&d.Hero(0)!=null,"hero summons in main field");Check(d.Skill(0),"manual skill available immediately on summon");
  var h=d.Hero(0);d.players[0].heroLevel=3;d.players[0].heroXp=17;h.hp=0;d.Tick(.05f);float death=d.time;Check(d.Hero(0)==null,"hero death begins respawn wait");for(int i=0;i<399;i++)d.Tick(.05f);Check(d.Hero(0)==null,"hero cannot revive early");for(int i=0;i<3;i++)d.Tick(.05f);Check(d.Hero(0)!=null&&d.players[0].heroLevel==3&&d.players[0].heroXp==17,"hero respawns with preserved level and XP");
  var xp=new BattleSimulation(c,"Human",deck,2,true){enableAI=false};xp.players[0].soul=10;xp.Summon(0);var hero=xp.Hero(0);hero.pos=new Vector2(3.5f,5.5f);hero.cooldown=0;var victim=xp.Spawn(c.Find("O01"),1,0,1,0,new Vector2(3.5f,6));victim.hp=1;xp.Tick(.05f);Check(xp.players[0].heroXp==10,"main-field kill awards living hero XP");
  var end=new BattleSimulation(c,"Human",deck,0,true){enableAI=false};end.Base(0).hp=0;end.Tick(.05f);Check(end.result==1,"base destruction ends battle");
  string temp=Path.Combine(Root,"artifacts/test-save/progress.json");Directory.CreateDirectory(Path.GetDirectoryName(temp));if(File.Exists(temp))File.Delete(temp);if(File.Exists(temp+".bak"))File.Delete(temp+".bak");var store=new ProgressStore(temp);Check(store.Reward("test",0,true)==0&&store.Data.stones==0,"practice never awards permanent currency");Check(store.Reward("test",0,false)==20&&store.Reward("test",0,false)==0,"victory reward is idempotent");Check(store.UpgradeUnit("H01")&&new ProgressStore(temp).Level("H01")==2,"permanent upgrade survives reload");
  Directory.CreateDirectory(Path.Combine(Root,"artifacts"));File.WriteAllLines(Path.Combine(Root,"artifacts/rule-checks.txt"),checks);Debug.Log("PROTOTYPE_CHECKS_PASSED "+checks.Count);}
 [MenuItem("Prototype/Build Windows")]
 public static void Windows(){Configure();Validate();Directory.CreateDirectory(Path.Combine(Root,"Builds/Windows"));var report=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{"Assets/Scenes/Boot.unity"},locationPathName=Path.Combine(Root,"Builds/Windows/BackpackRTS.exe"),target=BuildTarget.StandaloneWindows64,options=BuildOptions.Development});if(report.summary.result!=BuildResult.Succeeded)throw new Exception("Windows build failed: "+report.summary.result);Debug.Log("WINDOWS_BUILD_OK");}
 [MenuItem("Prototype/Build Android")]
 public static void Android(){Configure();Validate();string paths=Path.Combine(Root,"android-local-paths.json");if(File.Exists(paths)){var local=JsonUtility.FromJson<AndroidPaths>(File.ReadAllText(paths));EditorPrefs.SetString("AndroidSdkRoot",local.sdkRootPath);EditorPrefs.SetString("AndroidNdkRootR16b",local.ndkRootPath);EditorPrefs.SetString("JdkPath",local.jdkRootPath);EditorPrefs.SetBool("SdkUseEmbedded",false);EditorPrefs.SetBool("NdkUseEmbedded",false);EditorPrefs.SetBool("JdkUseEmbedded",false);var type=AppDomain.CurrentDomain.GetAssemblies().Select(a=>a.GetType("UnityEditor.Android.AndroidExternalToolsSettings")).FirstOrDefault(t=>t!=null);if(type!=null){type.GetProperty("sdkRootPath")?.SetValue(null,local.sdkRootPath);type.GetProperty("ndkRootPath")?.SetValue(null,local.ndkRootPath);type.GetProperty("jdkRootPath")?.SetValue(null,local.jdkRootPath);}}
  PlayerSettings.SetScriptingBackend(UnityEditor.Build.NamedBuildTarget.Android,ScriptingImplementation.IL2CPP);PlayerSettings.Android.targetArchitectures=AndroidArchitecture.ARM64;Directory.CreateDirectory(Path.Combine(Root,"Builds/Android"));EditorUserBuildSettings.buildAppBundle=false;var report=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{"Assets/Scenes/Boot.unity"},locationPathName=Path.Combine(Root,"Builds/Android/BackpackRTS-0.2.0.apk"),target=BuildTarget.Android,options=BuildOptions.Development});if(report.summary.result!=BuildResult.Succeeded)throw new Exception("Android build failed: "+report.summary.result);Debug.Log("ANDROID_BUILD_OK");}
 [Serializable] class AndroidPaths{public string sdkRootPath,ndkRootPath,jdkRootPath;}
}
