using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEditor.Build.Reporting;
using UnityEngine;
using BackpackRTS;

public static class PrototypeBuild {
 static string Root=>Directory.GetParent(Application.dataPath).FullName;
 static readonly List<string> checks=new List<string>();
 static void Check(bool yes,string name){if(!yes)throw new Exception("FAILED: "+name);checks.Add(name);Debug.Log("PASS: "+name);}
 public static void Configure(){PlayerSettings.companyName="RTS Prototype";PlayerSettings.productName="Backpack RTS";PlayerSettings.bundleVersion="0.4.0";PlayerSettings.defaultScreenWidth=540;PlayerSettings.defaultScreenHeight=960;PlayerSettings.fullScreenMode=FullScreenMode.Windowed;PlayerSettings.resizableWindow=false;PlayerSettings.defaultInterfaceOrientation=UIOrientation.Portrait;PlayerSettings.allowedAutorotateToLandscapeLeft=false;PlayerSettings.allowedAutorotateToLandscapeRight=false;PlayerSettings.allowedAutorotateToPortraitUpsideDown=false;PlayerSettings.runInBackground=false;
  PlayerSettings.SetApplicationIdentifier(UnityEditor.Build.NamedBuildTarget.Android,"com.hdh853.rtsproto");PlayerSettings.Android.bundleVersionCode=4;PlayerSettings.Android.minSdkVersion=AndroidSdkVersions.AndroidApiLevel26;PlayerSettings.Android.targetSdkVersion=AndroidSdkVersions.AndroidApiLevel35;
  var scene=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);new GameObject("Backpack RTS").AddComponent<PrototypeGame>();Directory.CreateDirectory(Path.Combine(Application.dataPath,"Scenes"));EditorSceneManager.SaveScene(scene,"Assets/Scenes/Boot.unity");EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene("Assets/Scenes/Boot.unity",true)};AssetDatabase.SaveAssets();}
 [MenuItem("Prototype/Validate rules")]
 public static void Validate(){checks.Clear();var c=Catalog.Load();var deck=c.DefaultDeck("Human");
  Check(c.units.Length==12&&c.cards.Length==8,"12 units and 8 shared cards");
  Check(c.units.All(u=>u.tiers.Length==5&&u.tiers.All(t=>t.hp>0&&t.damage>0&&t.spawnInterval>0&&t.detectionRange>t.range)),"60 tiers have independent stats and wider detection");
  Check(c.ValidDeck("Human",deck)&&!c.ValidDeck("Human",deck.Take(4).ToArray())&&!c.ValidDeck("Orc",deck),"eight-card faction deck validation");
  Check(!c.ValidDeck("Human",new[]{"H01","H01","H02","H03","mine","tower","fence","fire"}),"duplicate deck rejected");
  Check(c.MigrateDeck("Human",new[]{"H01","H02","H03","H04"}).SequenceEqual(deck),"legacy deck migrates to eight cards");
  var w=new BattleSimulation(c,"Human",deck,2,true){enableAI=false};Check(w.players[0].swaps==1,"initial refresh credit");Check(w.Swap(0,0),"refresh consumes one card");w.Tick(29.9f);Check(w.players[0].swaps==0,"refresh unavailable before 30 seconds");w.Tick(.11f);Check(w.players[0].swaps==1,"refresh recovers after 30 seconds");w.Tick(60);Check(w.players[0].swaps==1,"refresh does not accumulate");
  var hand=new BattleSimulation(c,"Human",deck,0,true){enableAI=false};bool unique=true;for(int i=0;i<100;i++){hand.players[0].hand[i%4]=null;hand.players[0].refill[i%4]=hand.time;hand.Tick(.05f);unique&=hand.players[0].hand.Where(k=>k!=null).Distinct().Count()==hand.players[0].hand.Count(k=>k!=null);}Check(unique,"100 refills never duplicate current hand");
  Check(hand.FreeMines(0)==3,"only three unbuilt friendly resource tiles initially");for(int y=0;y<10;y++)for(int x=0;x<10;x++)if(hand.Terrain(0,x,y)==1&&hand.At(0,x,y)==null)hand.AddBuilding("mine",0,0,x,y,false);hand.players[0].hand[0]="mine";hand.Tick(.9f);hand.Tick(.9f);Check(hand.FreeMines(0)==0&&!hand.players[0].hand.Contains("mine"),"full resource sites remove and prohibit mine card");
  var a=new BattleSimulation(c,"Human",deck,0,true){enableAI=false};a.players[0].hand=new[]{"H01","H02","mine","fire"};var gold=a.players[0].gold;
  Check(a.Width(0)==10&&a.Height(0)==24&&Enumerable.Range(0,24).Count(y=>a.IsHome(0,0,y))*10==100,"friendly construction expands to 100 cells");
  Check(!a.PlaceCard(0,0,0,3,11)&&a.players[0].gold==gold&&a.players[0].hand[0]=="H01","invalid placement preserves card and gold");
  var gesture=new PlacementGesture();gesture.Begin(0,0,2,4);Check(a.At(0,2,4)==null&&a.players[0].gold==gold,"pointer down does not build or pay");gesture.Move(false,-1,-1);Check(!gesture.Release(a,true,2,4)&&a.players[0].gold==gold,"leaving field cancels even after returning");
  gesture.Begin(0,0,2,4);Check(gesture.Release(a,true,2,4)&&a.players[0].gold==gold-5,"valid release commits placement once");Check(!gesture.Release(a,true,2,4),"second release cannot double spend");
  a.players[0].hand[0]="H01";gesture.Begin(0,0,2,4);var before=a.players[0].gold;Check(!gesture.Release(a,true,2,4)&&a.players[0].gold==before,"invalid release preserves resources");
  Check(a.At(0,3,4)!=null&&a.At(0,2,5)==null,"fixed building footprint cannot rotate");
  Check(a.Shape("mine").Length==1&&a.PlaceCard(0,2,0,8,2)&&a.players[0].gold==before-4,"one-cell mine placement costs four gold");a.Tick(1.1f);
  var mine=a.buildings.First(b=>b.team==0&&b.kind=="mine");for(int i=0;i<5;i++)a.BuyWorker(mine);Check(mine.workers==6&&!a.BuyWorker(mine),"mine workers capped at six");var m2=a.At(0,8,2);m2.workers=1;Check(!a.Merge(mine,m2)&&mine.alive&&m2.workers==1,"merge never loses excess workers");
  var b1=a.At(0,2,4);var b2=a.AddBuilding("H01",0,0,5,4);a.Tick(1.1f);b1.hp=b1.maxHp*.5f;b1.progress=6;b2.progress=2;Check(a.Merge(b1,b2)&&b2.tier==2&&Mathf.Abs(b2.hp/b2.maxHp-.75f)<.001f,"merge keeps weighted health");Check(Mathf.Abs(b2.progress-2)<.01f,"stat growth keeps production interval");Check(c.Find("H06").tiers[2].spawnInterval<c.Find("H06").tiers[0].spawnInterval*.5f,"production growth stays independent");
  var nav=new BattleSimulation(c,"Human",deck,0,true){enableAI=false};var nb=nav.AddBuilding("H01",0,0,2,4,false);nav.AddBuilding("H01",0,0,2,5,false);
  Check(nav.Navigable(0,new Vector2(2.5f,5))&&!nav.Navigable(0,new Vector2(2.5f,4.5f)),"building body blocked but shared border is walkable");Check(nav.SegmentClear(0,new Vector2(2,5),new Vector2(4,5)),"continuous corridor between adjacent buildings");Check(nav.TryExit(nb,out var exit)&&exit.y>nb.pos.y,"production exit faces enemy even with front neighbour");
  var wall=nav.AddBuilding("fence",0,0,6,5,false);int units=nav.fighters.Count;nav.Tick(20);Check(!nav.projectiles.Any(p=>p.source==wall)&&nav.BuildingTier(wall)==null,"fence neither shoots nor produces units");
  var spells=new BattleSimulation(c,"Human",deck,0,true){enableAI=false};spells.players[0].hand=new[]{"mining","rally","fire","tower"};var sm=spells.buildings.First(b=>b.team==0&&b.kind=="mine");float income=spells.Income(0);Check(spells.CastCard(0,0,0,sm.pos)&&Mathf.Abs(spells.Income(0)-(.35f+(income-.35f)*2))<.001f,"mining spell doubles worker income");
  var ally=spells.Spawn(c.Find("H01"),1,0,0,0,new Vector2(4,6));Check(spells.CastCard(0,1,0,ally.pos)&&ally.hasteUntil==spells.time+6,"rally applies timed buff");float sg=spells.players[0].gold;Check(!spells.CastCard(0,2,0,new Vector2(0,0))&&spells.players[0].gold==sg,"empty spell target preserves card and cost");var enemy=spells.Spawn(c.Find("O01"),1,0,1,0,new Vector2(5,6));float ehp=enemy.hp;Check(spells.CastCard(0,2,0,enemy.pos),"damage spell accepts enemy target");spells.Tick(.05f);Check(enemy.hp<=ehp-90,"damage spell applies damage");
  var chase=new BattleSimulation(c,"Human",deck,0,true){enableAI=false};var attacker=chase.Spawn(c.Find("H01"),1,0,0,0,new Vector2(3.5f,7));attacker.cooldown=0;attacker.stats=new TierDefinition{range=.55f,detectionRange=4,speed=1.2f,damage=10,attackInterval=1};var foe=chase.Spawn(c.Find("O01"),1,0,1,0,new Vector2(3.5f,9.5f));foe.stats=new TierDefinition{range=.3f,detectionRange=4,speed=0,damage=1,attackInterval=100};foe.cooldown=999;float original=foe.hp;for(int i=0;i<80;i++)chase.Tick(.05f);Check(attacker.pos.y>7.5f&&foe.hp<original,"detected out-of-range enemy is approached and attacked");
  var shots=new BattleSimulation(c,"Human",deck,0,true){enableAI=false};var shooter=shots.Spawn(c.Find("H02"),1,0,0,0,new Vector2(3,7));var victim=shots.Spawn(c.Find("O01"),1,0,1,0,new Vector2(3,9));shooter.cooldown=victim.cooldown=999;shooter.stats=new TierDefinition{range=3,speed=0,detectionRange=5};victim.stats=new TierDefinition{range=1,speed=0,detectionRange=4};float hp=victim.hp;
  shots.Launch(shooter,victim,30,new TierDefinition{range=3,projectile="line",projectileSpeed=4});shots.Tick(.1f);Check(victim.hp==hp&&shots.projectiles.Count==1,"projectile launch causes no immediate damage");for(int i=0;i<12;i++)shots.Tick(.05f);Check(victim.hp==hp-30,"projectile collision applies delayed damage");
  var backup=shots.Spawn(c.Find("O01"),1,0,1,0,new Vector2(3,10));backup.stats=victim.stats;backup.cooldown=999;float backupHp=backup.hp;shots.Launch(shooter,victim,25,new TierDefinition{range=4,projectile="line",projectileSpeed=5});victim.alive=false;for(int i=0;i<20;i++)shots.Tick(.05f);Check(backup.hp==backupHp-25,"dead original target leaves projectile to hit next enemy");
  var rear=shots.Spawn(c.Find("O01"),1,0,1,0,new Vector2(3,11));rear.stats=victim.stats;rear.cooldown=999;float rearHp=rear.hp;backupHp=backup.hp;shots.Launch(shooter,backup,20,new TierDefinition{range=5,projectile="pierce",projectileSpeed=5,pierce=2});for(int i=0;i<20;i++)shots.Tick(.05f);Check(backup.hp==backupHp-20&&rear.hp==rearHp-20,"piercing projectile hits two enemies exactly once");
  rearHp=rear.hp;shots.Launch(shooter,rear,15,new TierDefinition{range=5,projectile="blast",projectileSpeed=5,splash=1.2f,targetLimit=4});shots.Tick(.1f);Check(rear.hp==rearHp,"blast waits for arrival");for(int i=0;i<20;i++)shots.Tick(.05f);Check(rear.hp==rearHp-15,"blast damages enemies at arrival point");
  var d=new BattleSimulation(c,"Human",deck,2,true){enableAI=false};for(int i=0;i<100;i++)d.Tick(.05f);Check(d.fighters.Count(f=>f.alive&&f.team==2)==5,"dungeon has five fixed enemies without respawns");d.fighters.First(f=>f.team==2&&!f.boss).hp=0;d.Tick(.05f);Check(d.players[0].soul==0,"ordinary dungeon kill gives no soul");d.fighters.First(f=>f.boss).hp=0;d.Tick(.05f);Check(d.players[0].soul==10,"boss gives ten souls once");d.Tick(.05f);Check(d.players[0].soul==10,"boss reward not duplicated");Check(d.Summon(0)&&d.Hero(0)!=null&&d.Skill(0),"hero summons with immediately usable skill");d.players[0].heroLevel=3;d.players[0].heroXp=17;d.Hero(0).hp=0;d.Tick(.05f);for(int i=0;i<399;i++)d.Tick(.05f);Check(d.Hero(0)==null,"hero cannot revive early");for(int i=0;i<3;i++)d.Tick(.05f);Check(d.Hero(0)!=null&&d.players[0].heroLevel==3&&d.players[0].heroXp==17,"hero retains level and XP after respawn");
  var end=new BattleSimulation(c,"Human",deck,0,true){enableAI=false};end.Base(0).hp=0;end.Tick(.05f);Check(end.result==1,"base destruction ends battle");
  var v4=new BattleSimulation(c,"Human",deck,2,true){enableAI=false};var vm=v4.buildings.First(b=>b.team==0&&b.kind=="mine");var vm2=v4.AddBuilding("mine",0,0,8,2,false);
  Check(v4.WorkerCost(vm)==5&&v4.WorkerCost(vm2)==3,"worker cost depends on each mine count");v4.BuyWorker(vm);Check(v4.WorkerCost(vm)==8&&v4.WorkerCost(vm2)==3,"hiring at one mine never raises another mine cost");Check(c.workerCosts.SequenceEqual(new[]{3,5,8,12,17,23}),"worker curve is data driven and steeper");
  var mergeTarget=v4.AddBuilding("H01",0,0,2,4,false);mergeTarget.hp=mergeTarget.maxHp*.5f;mergeTarget.progress=3;v4.players[0].hand[0]="H01";float vg=v4.players[0].gold;var direct=new PlacementGesture();direct.Begin(0,0,2,4);
  Check(v4.CanUseAt(0,0,0,new Vector2(2.3f,4.2f),out var vwhy),"hand card previews direct merge on completed same tier");Check(direct.ReleaseAt(v4,true,new Vector2(2.3f,4.2f))&&mergeTarget.tier==2&&v4.players[0].gold==vg-5,"hand release merges once and charges card cost");Check(Mathf.Abs(mergeTarget.hp/mergeTarget.maxHp-.75f)<.001f&&mergeTarget.progress==0,"fresh merge material contributes full health and zero production progress");Check(!direct.ReleaseAt(v4,true,new Vector2(2.3f,4.2f))&&!v4.CanMergeCard(0,"H01",mergeTarget),"spent gesture and tier mismatch cannot merge again");
  var mirror=new[]{new Cell(0,0),new Cell(0,1),new Cell(1,0)};var icon=Footprint.Icon(mirror);Check(icon.Any(q=>q.x==1&&q.y==1)&&!icon.Any(q=>q.x==1&&q.y==0),"asymmetric hand icon matches forward world orientation");var body=Footprint.Body(new[]{new Cell(0,0),new Cell(1,0)});Check(Footprint.Contains(body,new Vector2(1,.5f))&&!Footprint.Contains(body,new Vector2(0,.5f)),"multi-cell body has no internal lane and keeps outer margin");Check(!Footprint.Contains(Footprint.Body(mirror),new Vector2(1.5f,1.5f)),"concave empty cell remains empty");
  var area=new BattleSimulation(c,"Human",deck,0,true){enableAI=false};foreach(var b in area.buildings.Where(b=>b.kind=="mine"))b.alive=false;var am1=area.AddBuilding("mine",0,0,2,5,false);var am2=area.AddBuilding("mine",0,0,4,5,false);var am3=area.AddBuilding("mine",0,0,7,5,false);area.players[0].hand[0]="mining";Check(area.CastCard(0,0,0,new Vector2(3.5f,5.5f))&&am1.boostUntil==10&&am2.boostUntil==10&&am3.boostUntil==0,"mining circle affects all and only mines within radius");
  var af=area.Spawn(c.Find("H01"),1,0,0,0,new Vector2(3.7f,8));Check(area.SpellTargets("rally",0,0,new Vector2(1.71f,8)).Contains(af)&&!area.SpellTargets("rally",0,0,new Vector2(1.69f,8)).Contains(af),"spell targeting preserves sub-tile world coordinates");
  var dungeon=new BattleSimulation(c,"Human",deck,2,true){enableAI=false};var du=dungeon.Spawn(c.Find("H01"),1,0,0,1,new Vector2(4.5f,1.5f));for(int i=0;i<100;i++)dungeon.Tick(.05f);Check(du.pos.y>3&&dungeon.Enemies(du).Any(e=>e.id==du.target),"dungeon unit advances toward same-field enemies beyond detection");
  var maze=new BattleSimulation(c,"Human",deck,0,true){enableAI=false};int[,] cells={{2,2},{4,8},{6,5},{3,9},{1,7},{0,3},{6,7},{2,6},{7,3},{7,4},{8,9},{6,2},{5,6},{4,7},{2,4},{5,3},{3,3}};for(int i=0;i<cells.GetLength(0);i++)maze.AddBuilding("fence",0,0,cells[i,0],cells[i,1],false);var walker=maze.Spawn(c.Find("H01"),1,0,0,0,new Vector2(4.5f,2.03f));walker.hero=true;walker.stats=new TierDefinition{range=.75f,speed=.95f,damage=1,attackInterval=100};for(int i=0;i<300;i++)maze.Tick(.05f);Check(walker.pos.y>5,"hero traverses previously stalling dense building layout without teleport");
  var kills=new BattleSimulation(c,"Human",deck,0,true){enableAI=false};var killer=kills.Spawn(c.Find("H02"),1,0,0,0,new Vector2(3,7));var killed=kills.Spawn(c.Find("O01"),1,0,1,0,new Vector2(3,8));killer.cooldown=killed.cooldown=999;killer.stats=new TierDefinition{speed=0};killed.stats=new TierDefinition{speed=0};kills.Launch(killer,killed,999,new TierDefinition{range=3,projectile="line",projectileSpeed=5});for(int i=0;i<10;i++)kills.Tick(.05f);Check(!killed.alive&&killer.kills==1,"projectile kill is credited to its source exactly once");
  string temp=Path.Combine(Root,"artifacts/test-save/progress.json");Directory.CreateDirectory(Path.GetDirectoryName(temp));if(File.Exists(temp))File.Delete(temp);if(File.Exists(temp+".bak"))File.Delete(temp+".bak");var store=new ProgressStore(temp);Check(store.Reward("test",0,true)==0&&store.Data.stones==0,"practice never awards permanent currency");Check(store.Reward("test",0,false)==20&&store.Reward("test",0,false)==0,"victory reward is idempotent");Check(store.UpgradeUnit("H01")&&new ProgressStore(temp).Level("H01")==2,"permanent upgrade survives reload");
  Directory.CreateDirectory(Path.Combine(Root,"artifacts"));File.WriteAllLines(Path.Combine(Root,"artifacts/rule-checks.txt"),checks);Debug.Log("PROTOTYPE_CHECKS_PASSED "+checks.Count);}
 [MenuItem("Prototype/Build Windows")]
 public static void Windows(){Configure();Validate();Directory.CreateDirectory(Path.Combine(Root,"Builds/Windows"));var report=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{"Assets/Scenes/Boot.unity"},locationPathName=Path.Combine(Root,"Builds/Windows/BackpackRTS.exe"),target=BuildTarget.StandaloneWindows64,options=BuildOptions.Development});if(report.summary.result!=BuildResult.Succeeded)throw new Exception("Windows build failed: "+report.summary.result);Debug.Log("WINDOWS_BUILD_OK");}
 [MenuItem("Prototype/Build Android")]
 public static void Android(){Configure();Validate();string paths=Path.Combine(Root,"android-local-paths.json");if(File.Exists(paths)){var local=JsonUtility.FromJson<AndroidPaths>(File.ReadAllText(paths));EditorPrefs.SetString("AndroidSdkRoot",local.sdkRootPath);EditorPrefs.SetString("AndroidNdkRootR16b",local.ndkRootPath);EditorPrefs.SetString("JdkPath",local.jdkRootPath);EditorPrefs.SetBool("SdkUseEmbedded",false);EditorPrefs.SetBool("NdkUseEmbedded",false);EditorPrefs.SetBool("JdkUseEmbedded",false);var type=AppDomain.CurrentDomain.GetAssemblies().Select(a=>a.GetType("UnityEditor.Android.AndroidExternalToolsSettings")).FirstOrDefault(t=>t!=null);if(type!=null){type.GetProperty("sdkRootPath")?.SetValue(null,local.sdkRootPath);type.GetProperty("ndkRootPath")?.SetValue(null,local.ndkRootPath);type.GetProperty("jdkRootPath")?.SetValue(null,local.jdkRootPath);}}
  PlayerSettings.SetScriptingBackend(UnityEditor.Build.NamedBuildTarget.Android,ScriptingImplementation.IL2CPP);PlayerSettings.Android.targetArchitectures=AndroidArchitecture.ARM64;Directory.CreateDirectory(Path.Combine(Root,"Builds/Android"));EditorUserBuildSettings.buildAppBundle=false;var report=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{"Assets/Scenes/Boot.unity"},locationPathName=Path.Combine(Root,"Builds/Android/BackpackRTS-0.4.0.apk"),target=BuildTarget.Android,options=BuildOptions.Development});if(report.summary.result!=BuildResult.Succeeded)throw new Exception("Android build failed: "+report.summary.result);Debug.Log("ANDROID_BUILD_OK");}
 [Serializable] class AndroidPaths{public string sdkRootPath="",ndkRootPath="",jdkRootPath="";}
}
